name: Notify Slack on PR

on:
  pull_request:
    types: [opened]

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Flat Payload to Slack
        uses: distributhor/workflow-webhook@v3
        with:  # <--- CHANGED FROM 'env' TO 'with'
          webhook_url: ${{ secrets.WORKFLOW_URL }}
          webhook_type: "json-extended"
          data: >-
            {
              "repo_fullname": "${{ github.event.repository.full_name }}",
              "pr_title": "${{ github.event.pull_request.title }}",
              "pr_author": "${{ github.event.pull_request.user.login }}",
              "pr_link": "${{ github.event.pull_request.html_url }}"
            }
